module.exports = {
    url: 'https://www.bet365.com/#/HO/',
    botaoDeLoginEmCima: '.hm-MainHeaderRHSLoggedOutWide_Login',
    botaoDeLoginNoCentro: '.lms-LoginModule ',
    digitarLogin: '.lms-StandardLogin_Username',
    digitarSenha: '.lms-StandardLogin_Password ',
    botaoDeLoginClicavel: '.lms-StandardLogin_LoginButtonText ',
    confirmeIdentidade: '.flexiField_Input,.flexiField_Input',
    campodeEmail: '#EmailAddress.flexiField_Input,.flexiField_Input',
    campoDataNascimento: '#DateOfBirthDay.flexiField_Input',
    campomesMesNascimento: '#DateOfBirthMonth.flexiField_Input',
    campomesAnoNascimento: '#DateOfBirthYear.flexiField_Input',
    campoCaptcha: '#CaptchaInput.flexiField_Input',
    segundoBotaoDeLoginClicavel: '#LogIn.accept-button',
    TerceiraTelaBotaoPesquisar: '.hm-MainHeaderRHSLoggedInWide_SiteSearchButton',
    botaoDePesquisa: '.hm-MainHeaderRHSLoggedInWide_SiteSearchButton',
    iframeSelector: '.lp-UserNotificationsPopup_Frame ',
    iframeURL: 'iframe[src="https://members.bet365.com/members/services/notifications/process"]',
    imagemCaptcha: '#CaptchaCode img'
}